version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.10
    - 7.13.17
    - 7.13.9
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.6
    - 24.1.7
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.0
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: uint8arrays
    versions:
    - 2.1.3
    - 2.1.4
  - dependency-name: did-resolver
    versions:
    - 3.0.1
    - 3.0.2
  - dependency-name: jsdoc-to-markdown
    versions:
    - 7.0.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  commit-message:
    prefix: chore
    include: scope
